/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendavideojuegogkj;

import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
//import static proyectointento4.GUIProyecto.panelCarrito;
//import static proyectointento4.GUIProyecto.panelFactura;

/**
 *
 * @author compu
 */
public class PnlCarrito extends javax.swing.JPanel {

DefaultTableModel dtmModelo;
PnlFactura panelFactura;
GUIFactura guiFactura;
//Factura factura;
static LinkedList<Double> factura;

    /**
     * Creates new form PnlCarrito
     */
    public PnlCarrito() {
        initComponents();
        pnlMostrarCarrito.setVisible(true);
        dtmModelo = new DefaultTableModel();
        dtmModelo.addColumn("Número");
        dtmModelo.addColumn("Nombre");
        dtmModelo.addColumn("Dispositivo");
        dtmModelo.addColumn("Precio");    
        tblInformacion.setModel(dtmModelo);
        lblRequisito.setEnabled(false);
        chkCarrito.setEnabled(false);
        btnRealizarCompra.setEnabled(false);
        panelFactura = new PnlFactura();
        factura= new LinkedList<>();
        pnlMostrarCarrito.setVisible(true);
        guiFactura = new GUIFactura();
        txtPrecio.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlMostrarCarrito = new javax.swing.JPanel();
        btnMostrarVideojuegos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInformacion = new javax.swing.JTable();
        btnRealizarCompra = new javax.swing.JButton();
        lblRequisito = new javax.swing.JLabel();
        chkCarrito = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();

        pnlMostrarCarrito.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrito"));

        btnMostrarVideojuegos.setText("Mostrar Carrito");
        btnMostrarVideojuegos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVideojuegosActionPerformed(evt);
            }
        });

        tblInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblInformacion);

        btnRealizarCompra.setText("Realizar Compra");
        btnRealizarCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarCompraActionPerformed(evt);
            }
        });

        lblRequisito.setBackground(new java.awt.Color(0, 204, 51));
        lblRequisito.setForeground(new java.awt.Color(0, 153, 0));
        lblRequisito.setText("desea eliminar la compra");

        chkCarrito.setText("Esta correcto el carrito");
        chkCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCarritoActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio Total");

        btnBorrar.setText("Eliminar Carrito");
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMostrarCarritoLayout = new javax.swing.GroupLayout(pnlMostrarCarrito);
        pnlMostrarCarrito.setLayout(pnlMostrarCarritoLayout);
        pnlMostrarCarritoLayout.setHorizontalGroup(
            pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarCarritoLayout.createSequentialGroup()
                .addGroup(pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMostrarCarritoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkCarrito)
                            .addComponent(btnRealizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMostrarCarritoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRequisito, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMostrarCarritoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMostrarCarritoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnMostrarVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMostrarCarritoLayout.setVerticalGroup(
            pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarCarritoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnMostrarVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCarrito)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMostrarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRealizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRequisito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMostrarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMostrarCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(528, 528, 528))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVideojuegosActionPerformed

        chkCarrito.setEnabled(true);
        dtmModelo.setRowCount(0);
        int j=0;      
        double precioTotal=0;
        for(Videojuego t: GUIProyecto.listaVideojuego){
         
        dtmModelo.addRow(new Object[]{j,t.getNombreJuego(),t.getNombreDispositivo(),t.getPrecio()});
        precioTotal= precioTotal+t.getPrecio();
           j++;
        }
        txtPrecio.setText(Double.toString(precioTotal));
        factura.add(precioTotal);
        btnBorrar.setEnabled(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarVideojuegosActionPerformed

    private void btnRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarCompraActionPerformed
     
      chkCarrito.setSelected(false);      
      dtmModelo.setRowCount(0);
      lblRequisito.setEnabled(false);
      btnRealizarCompra.setEnabled(false); 
      chkCarrito.setEnabled(false);
      txtPrecio.setText(null);
      panelFactura.setVisible(true);
     // pnlMostrarCarrito.setVisible(false);
      guiFactura.setVisible(true);
      GUIProyecto.listaVideojuego.clear();
      //panelFactura.setSize(800,800);
      //panelFactura.setLocation(100,-200);
      //add(panelFactura);
      //revalidate();
      //repaint();  

     
      
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarCompraActionPerformed

    private void chkCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCarritoActionPerformed

       
       if(chkCarrito.isSelected()){
          lblRequisito.setEnabled(true);
         
          btnRealizarCompra.setEnabled(true);
          btnBorrar.setEnabled(false);
       }
       else {
          lblRequisito.setEnabled(false);
          btnRealizarCompra.setEnabled(false); 
          btnBorrar.setEnabled(true);
       }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCarritoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    txtPrecio.setText(null);
    factura.clear();
    dtmModelo.setRowCount(0);
    GUIProyecto.listaVideojuego.clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnMostrarVideojuegos;
    private javax.swing.JButton btnRealizarCompra;
    private javax.swing.JCheckBox chkCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRequisito;
    private javax.swing.JPanel pnlMostrarCarrito;
    private javax.swing.JTable tblInformacion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
