/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendavideojuegogkj;

import javax.swing.JOptionPane;



/**
 *
 * @author compu
 */
public class PnlFactura extends javax.swing.JPanel {
    Factura factura2;
    int contador;
    /**
     * Creates new form PnlFactura
     */
    public PnlFactura() {
        initComponents();
        factura2 = new  Factura();
        
        pnlFacturaTerminada.setVisible(true);
        contador =0;
        btnGuardar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCredito = new javax.swing.ButtonGroup();
        btnDebito = new javax.swing.ButtonGroup();
        pnlFacturaTerminada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoTarjeta = new javax.swing.JComboBox<>();
        pnlCredito = new javax.swing.JPanel();
        rbtVisa = new javax.swing.JRadioButton();
        rbtVisaElectron = new javax.swing.JRadioButton();
        rbtMaestro = new javax.swing.JRadioButton();
        rbtMasterCard = new javax.swing.JRadioButton();
        rbtAmerican = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        pnlDebito = new javax.swing.JPanel();
        rbtBancoGuayas = new javax.swing.JRadioButton();
        rbtBancoPichincha = new javax.swing.JRadioButton();
        rbtBancoPacifico = new javax.swing.JRadioButton();
        lblMensajeCedula = new javax.swing.JLabel();
        lblMensajeNombre = new javax.swing.JLabel();
        lblMensajeDireccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlFacturaTerminada.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        jLabel1.setText("Nombre");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        jLabel2.setText("Cedula");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
        });

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });

        jLabel3.setText("Dirección");

        jLabel4.setText("Tipo de Tarjeta");

        cmbTipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credito", "debito" }));
        cmbTipoTarjeta.setSelectedIndex(-1);

        pnlCredito.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCredito.add(rbtVisa);
        rbtVisa.setText("Visa");

        btnCredito.add(rbtVisaElectron);
        rbtVisaElectron.setText("Visa Electron");

        btnCredito.add(rbtMaestro);
        rbtMaestro.setText("Maestro");

        btnCredito.add(rbtMasterCard);
        rbtMasterCard.setText("Master card");

        btnCredito.add(rbtAmerican);
        rbtAmerican.setText("American Express");

        javax.swing.GroupLayout pnlCreditoLayout = new javax.swing.GroupLayout(pnlCredito);
        pnlCredito.setLayout(pnlCreditoLayout);
        pnlCreditoLayout.setHorizontalGroup(
            pnlCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreditoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(rbtVisa)
                .addGap(61, 61, 61)
                .addComponent(rbtMasterCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(rbtAmerican)
                .addGap(30, 30, 30))
            .addGroup(pnlCreditoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(rbtVisaElectron)
                .addGap(77, 77, 77)
                .addComponent(rbtMaestro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCreditoLayout.setVerticalGroup(
            pnlCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreditoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtVisa)
                    .addComponent(rbtMasterCard)
                    .addComponent(rbtAmerican))
                .addGap(59, 59, 59)
                .addGroup(pnlCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtVisaElectron)
                    .addComponent(rbtMaestro))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnGuardar.setText("Aceptar ");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        pnlDebito.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnDebito.add(rbtBancoGuayas);
        rbtBancoGuayas.setText("Banco de Guayaquil");

        btnDebito.add(rbtBancoPichincha);
        rbtBancoPichincha.setText("Banco Pichincha");

        btnDebito.add(rbtBancoPacifico);
        rbtBancoPacifico.setText("Banco del Pacifico");

        javax.swing.GroupLayout pnlDebitoLayout = new javax.swing.GroupLayout(pnlDebito);
        pnlDebito.setLayout(pnlDebitoLayout);
        pnlDebitoLayout.setHorizontalGroup(
            pnlDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDebitoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(rbtBancoGuayas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(rbtBancoPichincha)
                .addGap(67, 67, 67))
            .addGroup(pnlDebitoLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(rbtBancoPacifico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDebitoLayout.setVerticalGroup(
            pnlDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDebitoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBancoGuayas)
                    .addComponent(rbtBancoPichincha))
                .addGap(37, 37, 37)
                .addComponent(rbtBancoPacifico)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        lblMensajeCedula.setForeground(new java.awt.Color(255, 0, 51));
        lblMensajeCedula.setText("*");

        lblMensajeNombre.setForeground(new java.awt.Color(255, 0, 51));
        lblMensajeNombre.setText("*");

        lblMensajeDireccion.setForeground(new java.awt.Color(255, 0, 51));
        lblMensajeDireccion.setText("*");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Mariana de Jesus y La Tola N64-78");

        javax.swing.GroupLayout pnlFacturaTerminadaLayout = new javax.swing.GroupLayout(pnlFacturaTerminada);
        pnlFacturaTerminada.setLayout(pnlFacturaTerminadaLayout);
        pnlFacturaTerminadaLayout.setHorizontalGroup(
            pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                                    .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(21, 21, 21)
                                    .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                                            .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                                                    .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtNombre)
                                                        .addComponent(txtDireccion))
                                                    .addGap(6, 6, 6)))
                                            .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblMensajeDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMensajeCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lblMensajeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(15, 15, 15))
                                        .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnlCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(btnGuardar)))
                    .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFacturaTerminadaLayout.setVerticalGroup(
            pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturaTerminadaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblMensajeDireccion))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pnlFacturaTerminadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(pnlDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlFacturaTerminada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(pnlFacturaTerminada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed


    try{
    factura2.setCedula(txtCedula.getText());
    factura2.setNombreComprador(txtNombre.getText());
    factura2.setDireccion(txtDireccion.getText());
    factura2.setTipoTarjeta((String)cmbTipoTarjeta.getSelectedItem());
    
    String tarjetaSeleccionada="";
    if(rbtAmerican.isSelected()){
        tarjetaSeleccionada ="American";
        contador=1;
    }
    if(rbtBancoGuayas.isSelected()){
        tarjetaSeleccionada ="Banco de Guayaquil";
         contador=1;
    }
    if(rbtBancoPacifico.isSelected()){
        tarjetaSeleccionada ="Banco del Pacifico";
        contador=1;
    }
    
    if(rbtBancoPichincha.isSelected()){
        tarjetaSeleccionada ="Banco Pichincha";
         contador=1;
    }
    if(rbtMaestro.isSelected()){
        tarjetaSeleccionada ="Maestro";
      contador=1;
    }
    if(rbtMasterCard.isSelected()){
        tarjetaSeleccionada ="MasterCard";
     contador=1;
    }
    if(rbtVisa.isSelected()){
        tarjetaSeleccionada ="Visa";
     contador=1;
    }
    if(rbtVisaElectron.isSelected()){
        tarjetaSeleccionada ="VisaElectron";
     contador=1;
    }
    

    factura2.setTarjetaUsada(tarjetaSeleccionada);

   pnlFacturaTerminada.setVisible(false);
  // JOptionPane.showMessageDialog(null,"Animal agregado exitosamente");
   //JOptionPane.showMessageDialog(null,"Exception"+factura2.getDireccion(),"Error",JOptionPane.ERROR_MESSAGE);
   JOptionPane.showMessageDialog(null,"Nombre del comprador: "+factura2.getNombreComprador()+"\n"
           +"Cedula: "+factura2.getCedula()+"\n"
           +"Dirección: "+factura2.getDireccion()+"\n"
           +"Tipo de pago: "+factura2.getTipoTarjeta()+"\n"                   
           +"Tarjeta a usar: "+factura2.getTarjetaUsada()+"\n"
           +"Precio Total a pagar: "+PnlCarrito.factura.get(0),"Factura",-1);

   limpiarGUI();
   
   }
    catch(NumberFormatException nfe){
         JOptionPane.showMessageDialog(null,"La edad"
                + " deben ser un número entero","Error",JOptionPane.WARNING_MESSAGE);       
       }
    catch (NullPointerException npe){
           
           JOptionPane.showMessageDialog(null,"error al crear el objeto");
       } 
    catch (Exception e){
           
           JOptionPane.showMessageDialog(null,"Exception"+e.toString(),"Error",JOptionPane.ERROR_MESSAGE);
       } 
    //pnlFacturaTerminada.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased

    if(Verificacion.verificar(txtCedula.getText())){
    
    String mayor=txtCedula.getText().substring(0,2);
    int comparacion = Integer.parseInt(mayor);   
    
          if(comparacion<=24){        
          btnGuardar.setEnabled(true);
          lblMensajeCedula.setVisible(false);
          JOptionPane.showMessageDialog(null,"Cedula valida","Mensaje",-1);
          }
      
     }
     else{
       //  JOptionPane.showMessageDialog(null,txtCedula.getText().length(),"Error",-1);
         lblMensajeCedula.setVisible(true);
         btnGuardar.setEnabled(false);
     }


        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased

        if(Verificacion.nombreAceptado(txtNombre.getText())){
            lblMensajeNombre.setVisible(false);
           btnGuardar.setEnabled(true);
        }
        else{
            lblMensajeNombre.setVisible(true);
           btnGuardar.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased

         if(Verificacion.direccionAceptada(txtDireccion.getText())){
            lblMensajeDireccion.setVisible(false);
          btnGuardar.setEnabled(true);
         }
        else{
            lblMensajeDireccion.setVisible(true);
          btnGuardar.setEnabled(false);
          }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyReleased


    
    public void limpiarGUI(){
        
        txtCedula.setText(null);
        txtDireccion.setText(null);
        txtNombre.setText(null);
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnCredito;
    private javax.swing.ButtonGroup btnDebito;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTipoTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMensajeCedula;
    private javax.swing.JLabel lblMensajeDireccion;
    private javax.swing.JLabel lblMensajeNombre;
    private javax.swing.JPanel pnlCredito;
    private javax.swing.JPanel pnlDebito;
    private javax.swing.JPanel pnlFacturaTerminada;
    private javax.swing.JRadioButton rbtAmerican;
    private javax.swing.JRadioButton rbtBancoGuayas;
    private javax.swing.JRadioButton rbtBancoPacifico;
    private javax.swing.JRadioButton rbtBancoPichincha;
    private javax.swing.JRadioButton rbtMaestro;
    private javax.swing.JRadioButton rbtMasterCard;
    private javax.swing.JRadioButton rbtVisa;
    private javax.swing.JRadioButton rbtVisaElectron;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

   
}
